### ISSUE TITLE
Custom monitoring improvement task list

### ISSUE THREAD

**Issue by huanggze** [kubesphere/console#276]
# Remove unneeded fields (2/2)
- Graph panel: `id` (?), `legend`, `xaxis`, `shows`
![image](https://user-images.githubusercontent.com/22350668/82727467-58f0a600-9d1d-11ea-93b0-bcde038c7f34.png)

![image](https://user-images.githubusercontent.com/22350668/82727245-e4693780-9d1b-11ea-9adc-a66f0159752f.png)

![image](https://user-images.githubusercontent.com/22350668/82727386-c4864380-9d1c-11ea-8de6-4d41a9437e29.png)

- Row panel: `panels`

![image](https://user-images.githubusercontent.com/22350668/82729221-3fa12700-9d28-11ea-838a-5fa3e42b1b3e.png)

# Default interval between samples: 20s => 1m
![image](https://user-images.githubusercontent.com/22350668/82725124-6dc53d80-9d0d-11ea-9d9e-a7965c802054.png)
# More axis units
 [Ref: Grafana](https://github.com/grafana/grafana/blob/master/packages/grafana-data/src/valueFormats/categories.ts) 
 - none
 - percent (0-100)
 - percent (0.0-1.0)
 - data (IEC)
   - bytes
   - kibibytes
   - mebibytes
   - gibibytes
 - data (Metric)
   - bytes
   - kilobytes
   - megabytes
   - gigabytes   

![image](https://user-images.githubusercontent.com/22350668/82726712-766f4100-9d18-11ea-800e-03ddba235fb7.png)

![image](https://user-images.githubusercontent.com/22350668/82726762-d82fab00-9d18-11ea-94ef-cd098b0ab292.png)

# Suggest labels and values
![image](https://user-images.githubusercontent.com/22350668/82004929-a4101680-9696-11ea-9a1b-77107af710ed.png)

#  Never set random CRD name
MySQL Overview => mysql-overview-xxxxx
![image](https://user-images.githubusercontent.com/22350668/82728786-306caa00-9d25-11ea-8b03-33868ff8c5b4.png)

# Misleading save button
![image](https://user-images.githubusercontent.com/22350668/82729175-f7820480-9d27-11ea-899e-36c559720423.png)

**Comment by justahole** [comment]
- [x] Never set random CRD name

**Comment by justahole** [comment]
> # Remove unneeded fields (2/2)
> * Graph panel: `id` (?), `legend`, `xaxis`, `shows`
id is useful for React

**Comment by huanggze** [comment]
- display problem for long text
![image](https://user-images.githubusercontent.com/22350668/83734158-321d6280-a681-11ea-8970-96a5a4a6f2bc.png)
- add description for singlestat chart

**Comment by huanggze** [comment]
Must-do Items:
- [ ] Suggest labels and values
- [ ] Display problem for long text
- [ ] Remove unused fields `refresh` and `templatings` ( `time` can be kept if it is used)
- [ ] There is one metric producing two lines, but they aren't properly showed
- [ ] Chinese title
- [ ] Input matching problem
